version: '3.4'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
    - ../backend/secret.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
